### ISSUE TITLE
Pomyłka w przypisywaniu funkcji

### ISSUE THREAD

**Issue by komosinskid** [pbiecek/AdvancedR2018#85]
![image](https://user-images.githubusercontent.com/32815122/40277046-a236f55a-5c18-11e8-814f-3f39ed7fbee1.png)

Zostałem przypisany do funkcji hugo_read_data, a chciałem do hugo_clean_data. Na początku rzeczywiście chciałem to pierwsze, ale potem zobaczyłem, że jest jeszcze wolne coś ciekawszego i chciałem na to zmienić. Nie wiedziałem, jednak w jaki sposób miałbym to dokładnie zmienić, ponieważ nie dało się skreślić poprzedniego mojego wyboru, ponieważ on wówczas jeszcze "nie istniał". Napisałem o tym problemie w drugim wyborze funkcji w komentarzu, na co chyba Pan po prostu nie zwrócił uwagi. (wklejam poglądowy obrazek). Czy mogę zatem się zamienić - czyli zwolnić hugo_read_data, a wziąć hugo_clean_data. Stworzyłem stosowne zapytanie pull request.

Pozdrawiam,
DK

**Comment by pbiecek** [comment]
wciąż jest konflikt
najpierw przypisał się pan do hugo_read_data
wysłał pan chwilę później drugie przypisanie do hugo_clean_data, ale musiał zrobić pan to z innego strumienia, ponieważ była to operacja na nieaktualnym pliku (nie było w niej pana poprzedniego komita), dlatego był konflikt w komitach i nie mogłem połączyć obu zmian, zmiany rozpatruję po kolei i drugą musiałem odrzucić.
teraz ponownie jest konflikt, do hugo_clean_data w między czasie przypisała się  Eliza K (19h temu a więc przed tym issue i przed trzecim komitem co byóo widać w pull request). Dlatego ponownie zamykam ten komit.
