### ISSUE TITLE
Problem z odczytaniem wykresu powstałego przy użyciu funkcji plot()

### ISSUE THREAD

**Issue by golawskaj** [pbiecek/AdvancedR2018#98]
Przy zapisie wykresu powstałego przy użyciu funkcji plot(), udaje się go ponownie narysować, jednak po zapisaniu go w postaci .rda i ponownym załadowaniu staje się to niemożliwe, mimo iż znajduje się on w globalnym środowisku. Przykładowy kod:

```
plot(1:10)
wykres <- recordPlot()
invisible(dev.off())
save(wykres, file = "wykres.rda")
wykres
rm(wykres)
load("wykres.rda")
replayPlot(wykres)
# Error: NULL value passed as symbol address
```

To samo dzieje się przy użyciu funkcji saveRDS() i readRDS(). Teoretycznie dla wersji R >=3.3.0 powinno być to możliwe.

Przy zapisie wykresów powstałych przy użyciu pakietu ggplot2 w podobny sposób nie ma takiego problemu.
@pbiecek

**Comment by pbiecek** [comment]
U mnie funkcja replayPlot() powoduje błąd, tylko jeżeli wykonam ją w tej samej sesji co recordPlot()
Jeżeli zrobię recordPlot()
zamknę R i na nowo uruchomię sesje to już samo wpisanie
wykres
powoduje poprawne wyświetlenei wykresu

**Comment by golawskaj** [comment]
Rzeczywiście w ten sposób działa. Dziękuję bardzo za pomoc!
